defaults:
  - radial_basis: gaussian

_target_: schnetpack.representation.FieldSchNet
n_atom_basis: 128
n_interactions: 5
external_fields: []
response_properties: ${globals.response_properties}
shared_interactions: False
cutoff_fn:
  _target_: schnetpack.nn.cutoff.CosineCutoff
  cutoff: ${globals.cutoff}