defaults:
  - radial_basis: gaussian

_target_: schnetpack.representation.SchNet
n_atom_basis: 128
n_interactions: 6
cutoff_fn:
  _target_: schnetpack.nn.cutoff.CosineCutoff
  cutoff: ${globals.cutoff}